### PR TITLE
MPDX-7023 move logic to new library

### PR DESCRIPTION
**Pull request by gyasistory**
https://jira.cru.org/browse/MPDX-7023

### CODE REVIEW

**Comment by frett** [comment]
I thought we were going to continue to maintain the library logic within the current mpdx-android repo, and just setup publishing the library from there.

**Comment by gyasistory** [comment]
> I thought we were going to continue to maintain the library logic within the current mpdx-android repo, and just setup publishing the library from there.

@frett this isn't ready for review.  I was just setting it up once the internal library is complete.

**Comment by frett** [comment]
I mean, I don't think this github repo project is even necessary anymore

**Comment by gyasistory** [comment]
> I mean, I don't think this github repo project is even necessary anymore

@frett not sure

**Pull request closed without merging**
